---
title: "Model_fitting"
author: "Xiaoliang Zhang"
date: "29/09/2020"
output: pdf_document
---

```{r}
rm(list = ls())

library(gdata)
library(dplyr)
library(MASS)
library(rpart)
library(randomForest)
library(glmnet)
library(e1071)
library(caret)
library(gbm)
library(RSQLite)
library(sqldf)

train = read.csv("train_clean1.csv",sep = ',',row.names = NULL,header = TRUE,stringsAsFactors = FALSE)
test = read.csv("test_clean1.csv",sep = ',',row.names = NULL,header = TRUE,stringsAsFactors = FALSE)
predict = read.csv("baseline2.txt",sep = ',',row.names = NULL,header = TRUE,stringsAsFactors = FALSE)

check = read.csv("result_guassian.csv",sep = ',',row.names = NULL,header = TRUE,stringsAsFactors = FALSE)
```

```{r}

for (i in 1:nrow(train)) {
  x <- train$confirmed[i]
  if(x==""){
   train$confirmed[i] = x
  }
  else{
    z <- unlist(strsplit(x,'.',fixed=TRUE))
    y <- paste(z,collapse = "-")
    train$confirmed[i] <- y
  }
}
train$confirmed<-as.Date(train$confirmed,format = "%d-%m-%Y")




for (i in 1:nrow(test)) {
  x <- test$confirmed[i]
  if(x==""){
   test$confirmed[i] = x
  }
  else{
    z <- unlist(strsplit(x,'.',fixed=TRUE))
    y <- paste(z,collapse = "-")
    test$confirmed[i] <- y
  }
}
test$confirmed<-as.Date(test$confirmed,format = "%d-%m-%Y")
```

```{r}
train <- na.omit(train)
train <- sqldf('select * from train where duration <=30')
```



```{r}
train$city = NULL
train$X = NULL
train$province = NULL

test$city = NULL
test$X=NULL 
test$province = NULL
###################################
col_order <- c("duration","age","sex","country","V1","confirmed","high_fever","low_fever","breath","chest","throat","diarrhea","cold","nose","pneumonia","sputum","muscle","cough","discomfort","weak","vomit","flu","no.symptom")
train <- train[,col_order]

# test$discomfort = NULL
# train$discomfort = NULL

# test$high_fever = NULL
# train$high_fever = NULL

# test$nose=NULL
# train$nose=NULL   #exist = 1.90

# test$diarrhea = NULL
# train$diarrhea =NULL

# test$weak = NULL
# train$weak =NULL


# test$high_fever =NULL
# train$high_fever =NULL

# train$muscle=NULL
# test$muscle = NULL

# train$chest =NULL
# test$chest =NULL

train$sputum = NULL
test$sputum = NULL

train$breath =NULL
test$breath =NULL


# test$nose =NULL
# train$nose = NULL


# Make confirmed a Datetime object
str(train)

```

```{r}
uLevels <- function(names){
  for(c in names){
    print(c)
    train[,c] <<- factor(as.character(train[,c]))
    test[,c] <<- factor(as.character(test[,c]))
    map <- mapLevels(x=list(train[,c], test[,c]), codes=FALSE, combine=TRUE)
    mapLevels(train[,c]) <<- map
    mapLevels(test[,c]) <<- map
  }
}
# colnames(test)
uLevels(c('V1','sex','confirmed','country'))


```

```{r}
mtry_def <- floor(sqrt(ncol(train)*.75))
t_grid <- expand.grid(mtry = c(mtry_def))

```


```{bash}

```


```{r}

forest = randomForest(duration ~ ., data = train,na.action=na.roughfix,ntree=800)


print(forest)
```

```{r}

importance(forest)
varImpPlot(forest)
```

```{r}
floor(sqrt(ncol(train)-1))
mtry <- tuneRF(train[-1],train$duration,stepFactor = 1.5,improve = 0.1,trace = TRUE,plot=TRUE)
best.m<- mtry[mtry[,2]==min(mtry[,2]),1] # mtry =22
```
```{r}
# train[-1]

```


```{r}
# train
```


```{r}
set.seed(123)
model.forest <- randomForest(duration ~ ., data = train,na.action=na.roughfix,ntree=2000,mtry=4,importance=TRUE)
print(model.forest)
```


```{r}

```



```{r}
plot(model.forest)
```

```{r}
predict$duration = predict(model.forest, newdata = test)
write.csv(predict,"predictedRF.csv",row.names=FALSE)
```

```{r}
round(RMSE(predict$duration,model.forest$predicted))
```


# BOOSTING TREE

```{r}

boost <- gbm(duration ~ ., data = train,distribution = "Gaussian",interaction.depth = 6,shrinkage = 0.1, n.minobsinnode = 10)

print(boost)
```

```{r}
predict$duration = predict(boost, newdata = test)
write.csv(predict,"predicted_BT.csv",row.names=FALSE)
```



```{r}
library(faraway)
pairs(train)
round(cor(seatpos),2)
```

```{r}

```




```{r}
trControl <- trainControl(method = "cv", number = 10,search = "grid")

```



```{r}
set.seed(1234)


rf_default <- train(duration~.,data = train,method = "rf",trControl = trControl)

print(rf_default)
```

```{r}
set.seed(1234)

tuneGrid <- expand.grid(.mtry = c(1: 10))
rf_mtry <- train(duration~.,data = train,method = "rf",tuneGrid = tuneGrid,trControl = trControl,importance = TRUE,nodesize = 14,ntree = 300)
print(rf_mtry)
```

```{r}
rf_mtry$bestTune$mtry
best_mtry <- rf_mtry$bestTune$mtry
```
```{r}
store_maxnode <- list()
tuneGrid <- expand.grid(.mtry = best_mtry)
for (maxnodes in c(5: 15)) {
    set.seed(1234)
    rf_maxnode <- train(duration~.,
        data = train,
        method = "rf",
        tuneGrid = tuneGrid,
        trControl = trControl,
        importance = TRUE,
        nodesize = 14,
        maxnodes = maxnodes,
        ntree = 300)
    current_iteration <- toString(maxnodes)
    store_maxnode[[current_iteration]] <- rf_maxnode
}
results_mtry <- resamples(store_maxnode)
summary(results_mtry)

```
```{r}
store_maxtrees <- list()
for (ntree in c(250, 300, 350, 400, 450, 500, 550, 600, 800, 1000, 2000)) {
    set.seed(5678)
    rf_maxtrees <- train(duration~.,
        data = train,
        method = "rf",
        tuneGrid = tuneGrid,
        trControl = trControl,
        importance = TRUE,
        nodesize = 14,
        maxnodes = 24,
        ntree = ntree)
    key <- toString(ntree)
    store_maxtrees[[key]] <- rf_maxtrees
}
results_tree <- resamples(store_maxtrees)
summary(results_tree)
```

```{r}

```


```{r}


MSE.matrix = matrix(NA,nrow = 200,ncol = 4)
colnames(MSE.matrix) = c("MSE.tree","MSPE.tree","MSE.forest","MSPE.forest")

```

```{r}
# Train-valid split
for (r in 1: 200) {
  train_index = sample(1:nrow(train),0.7*nrow(train))
  train_data = train[train_index,]
  valid_data = train[-train_index,]
  
  model.tree <- rpart(duration ~ ., data = train_data)
  # MSE of the train data
  
  MSE.matrix[r,1] = mean((predict(model.tree,data = train_data) - train_data$duration)^2)
  # MSE of the valid data
  MSE.matrix[r,2] = mean((predict(model.tree,newdata = valid_data) - valid_data$duration)^2)
  
  # Random Forest Regression
  model.forest = randomForest(duration ~ ., data = train_data)
  # MSE of the train data
  MSE.matrix[r,3] = mean((predict(model.forest,data = train_data) - train_data$duration)^2)
  # MSE of the valid data
  MSE.matrix[r,4] = mean((predict(model.forest,newdata = valid_data) - valid_data$duration)^2)
}
print(apply(MSE.matrix,2,mean))

```
# only contain uncomfortable: 
 MSE.tree   MSPE.tree  MSE.forest MSPE.forest 
10.46612521 24.10509171 17.86405197 18.39009752

# 

